In [1]:
import numpy as np


In [2]:
arr = np.array([3,4,5,6,33])

In [4]:
np.mean(arr)

np.float64(10.2)

In [5]:
np.min(arr)

np.int64(3)

In [6]:
np.max(arr)

np.int64(33)

In [7]:
np.std(arr)

np.float64(11.443775600735973)

In [8]:
np.var(arr)

np.float64(130.95999999999998)

In [9]:
np.sum(arr)

np.int64(51)

In [10]:
np.prod(arr)

np.int64(11880)

In [12]:
np.median(arr)

np.float64(5.0)

In [17]:
np.percentile(arr,100)

np.float64(33.0)

In [15]:
np.subtract(arr,10)

array([-7, -6, -5, -4, 23])

In [ ]:
np.argmin(arr) #returns index

np.int64(0)

In [19]:
arr

array([ 3,  4,  5,  6, 33])

In [20]:
np.argmax(arr)

np.int64(4)

In [21]:
arr3 = np.array([1,2,2,2,44,44,44,3])
arr3

array([ 1,  2,  2,  2, 44, 44, 44,  3])

In [22]:
np.unique(arr3)

array([ 1,  2,  3, 44])

In [23]:
np.cumsum(arr3)

array([  1,   3,   5,   7,  51,  95, 139, 142])

In [25]:
np.linspace(arr3,2)

array([[ 1.        ,  2.        ,  2.        ,  2.        , 44.        ,
        44.        , 44.        ,  3.        ],
       [ 1.02040816,  2.        ,  2.        ,  2.        , 43.14285714,
        43.14285714, 43.14285714,  2.97959184],
       [ 1.04081633,  2.        ,  2.        ,  2.        , 42.28571429,
        42.28571429, 42.28571429,  2.95918367],
       [ 1.06122449,  2.        ,  2.        ,  2.        , 41.42857143,
        41.42857143, 41.42857143,  2.93877551],
       [ 1.08163265,  2.        ,  2.        ,  2.        , 40.57142857,
        40.57142857, 40.57142857,  2.91836735],
       [ 1.10204082,  2.        ,  2.        ,  2.        , 39.71428571,
        39.71428571, 39.71428571,  2.89795918],
       [ 1.12244898,  2.        ,  2.        ,  2.        , 38.85714286,
        38.85714286, 38.85714286,  2.87755102],
       [ 1.14285714,  2.        ,  2.        ,  2.        , 38.        ,
        38.        , 38.        ,  2.85714286],
       [ 1.16326531,  2.        

In [26]:
np.log(arr)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 3.49650756])

In [27]:
np.exp(arr3)

array([2.71828183e+00, 7.38905610e+00, 7.38905610e+00, 7.38905610e+00,
       1.28516001e+19, 1.28516001e+19, 1.28516001e+19, 2.00855369e+01])