In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9], [7,8,9]])

In [3]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [4]:
flat = myarr.flatten()

In [5]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 8, 9])

In [6]:
flat[0]

np.int64(1)

In [9]:
flat[3:7]

array([4, 5, 6, 7])

In [10]:
flat[:5]

array([1, 2, 3, 4, 5])

In [11]:
flat[3:]

array([4, 5, 6, 7, 8, 9, 7, 8, 9])

In [12]:
flat[::2]

array([1, 3, 5, 7, 9, 8])

In [13]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 8, 9])

In [15]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9], [7,8,9]])
arr2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [17]:
flated2 =arr2.flatten()
flated2

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 8, 9])

In [19]:
d = flated2[3:7]

In [20]:
d


array([4, 5, 6, 7])

In [21]:
d[0] = 100
d

array([100,   5,   6,   7])

In [22]:
flated2

array([  1,   2,   3, 100,   5,   6,   7,   8,   9,   7,   8,   9])

In [ ]:
f = flated2[3:7].copy() # copy() method creates a new array that is independent of the original array. Modifying the copied array will not affect the original array.
f

array([100,   5,   6,   7])

In [24]:
f[1] = 200
f

array([100, 200,   6,   7])

In [25]:
flated2

array([  1,   2,   3, 100,   5,   6,   7,   8,   9,   7,   8,   9])

In [29]:
flated2[[1,4,6]] # fancy indexing

array([2, 5, 7])

In [30]:
flated2[flated2 > 5] # boolean indexing

array([100,   6,   7,   8,   9,   7,   8,   9])