In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#axis 0 is for column wise operation
print("for axis 0")
print(arr[0])
sum = np.sum(arr,axis=0)
print(sum)

#axis 1 is for row wise operation
print("for axis 1")

print(arr[1])
sum = np.sum(arr,axis=1)
print(sum)

for axis 0
[1 2 3]
[12 15 18]
for axis 1
[4 5 6]
[ 6 15 24]


In [9]:
arr[0][1]


np.int64(2)

In [ ]:
arr[0,1] # alternative way to access element at 0th row and 1st column

np.int64(2)

In [11]:
arr[0:2, 1:3]  #slicing 0th and 1st row and 1st and 2nd column

array([[2, 3],
       [5, 6]])

In [12]:
#indexing 3d array
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
print(arr3d.shape)  #shape of 3d array

(2, 2, 3)


In [14]:
print(arr3d[0])  # first 2d array

[[1 2 3]
 [4 5 6]]


In [15]:
print(arr3d[0,1,2])

6


In [16]:
print(arr3d[:,1,:])  #slicing 3d array to get all rows of 1st column

[[ 4  5  6]
 [10 11 12]]
