In [11]:
import numpy as np

In [12]:
!pip install numpy


In [22]:
arr = np.array([1,2,3,4,5]) #1d array
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [23]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2d array
print(arr1)
print(type(arr1))
print(arr1.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
(2, 5)


In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.full((2,3,4),7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [27]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.arange(10,55,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [30]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [42]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9], [7,8,9]])

In [43]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [44]:
myarr.shape

(4, 3)

In [45]:
myarr.size

12

In [46]:
myarr.ndim

2

In [47]:
myarr.dtype

dtype('int64')

In [48]:
myarr1 = np.array([[1,2,3],[4,5,6],[7,8,9], [7,8,9]], dtype=np.float32)

In [50]:
print(myarr.dtype)
print(myarr1.dtype)


int64
float32


In [51]:
myarr1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
myarr1 = arr.astype(np.int32) #convert float array to int array
print(myarr1.dtype)

int32


In [59]:
myarr1

array([1, 2, 3, 4, 5], dtype=int32)

In [60]:
myarr2 = np.array([[1,2,3],[4,5,6],[7,8,9], [7,8,9]])

In [61]:
myarr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [64]:
reshaped = myarr2.reshape(3,4)
reshaped

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 7, 8, 9]])

In [65]:
myarr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [67]:
reshaped = myarr2.reshape(6,2)
reshaped

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 7],
       [8, 9]])

In [68]:
reshaped = myarr2.reshape(2,6)
reshaped

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [69]:
flattern = myarr2.flatten() 

In [70]:
flattern

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 8, 9])