In [1]:
#create 3*3 matrix

In [2]:
import numpy as np

In [4]:
arr = np.array([[22,33,44],[23,23,45],[56,78,89]])
arr

array([[22, 33, 44],
       [23, 23, 45],
       [56, 78, 89]])

In [5]:
arr.shape

(3, 3)

In [6]:
arr2 = np.array([1.1,2.2,3.3,4.4,5.5,6.6])
arr2

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])

In [12]:
#floats to integers
arr2.astype(int)
arr2

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])

In [18]:
print(type(arr2))
arr2.dtype

<class 'numpy.ndarray'>


dtype('float64')

In [16]:
arr3 = np.array([1,2,3,4,5,6])
arr3


array([1, 2, 3, 4, 5, 6])

In [26]:
#fancy indexing to get even numbers
arr3[[1,3,5]]


array([2, 4, 6])

In [27]:
arr4 = np.array([1,2,3,4,5,6,7,8,9])
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr4[arr4>5]

array([6, 7, 8, 9])